### ISSUE TITLE
coroutine分支问题

### ISSUE THREAD

**Issue by cloudfreexiao** [zhandouxiaojiji/behavior3lua#1]
请问下 coroutine 分支 为什么不合并到主干 感觉 coroutine 比较符合 lua 的风格

**Comment by zhandouxiaojiji** [comment]
用coroutine去实现RUNNING状态确实很简单，也不容易出错。但毕竟创建协议还是有代价的。如果只是单纯的用它来做AI，还是可以的。
但是我还是希望行为树的应该能广泛一些，比如做技能、子弹的效果，可能一场战斗下来就会创建成千上万个协程，在服务器不可能允许这种情况的出现，所以我最后还是采取记录节点运行状态的方式去RUNNING。

**Comment by cloudfreexiao** [comment]
明白了 谢谢 解答
