### ISSUE TITLE
动作节点running状态什么时候更新

### ISSUE THREAD

**Issue by 80after** [zhandouxiaojiji/behavior3lua#10]
比如Sequence节点，如果其第一个孩子节点第一次返回是running状态，那本次tick直接返回了，下次tick进来后会拿上一次的返回结果判断，如果是running则又直接return了，那这里岂不是死循环了？ 因为后续不会去执行running节点了。

**Comment by zhandouxiaojiji** [comment]
下次tick进来不是拿上次的结果判断，而是重新运行返回新的结果
https://github.com/zhandouxiaojiji/behavior3lua/blob/1ad505e0ea3e996767a7756160e5a110c611ffed/behavior3/behavior_tree.lua#L36-L40

**Comment by 80after** [comment]
好的，这里看错了。。 那我看Parallel节点好像不支持孩子节点同时运行吧，只能一个个运行，失败了也继续？

**Comment by zhandouxiaojiji** [comment]
是的，这个是假的并行，只是为了运行所有的子节点

**Comment by 80after** [comment]
这里不符合我的应用场景，我改成了真的并行，可以配置成功、失败条件，及子节点完成后是否继续执行三个参数。 
`
-- Parallel
--

local bret = require 'behavior3.behavior_ret'

local M = {
    name = 'Parallel',
    type = 'Composite',
    desc = '并行执行',
    args = {
        { 'failCondition', 'string', '失败条件' }, -- FAIL_ON_ONE、FAIL_ON_ALL
        { 'successCondition', 'string', '成功条件' }, -- SUCCEED_ON_ONE、SUCCEED_ON_ALL
        { 'childFinishContiCond', 'string', '子节点结束继续条件' } -- CHILDFINISH_ONCE、CHILDFINISH_LOOP
    },
    doc = [[
        并行的执行其子节点
    ]]
}
function M.run(node, env)
    local ret
    local args = node.args
    local failCount, successCount, childCount = 0, 0, #node.children
    for i = 1, childCount do
        local child = node.children[i]
        local childRet = node:getChildRet(env, child.id)
        local r = childRet

        if childRet == bret.INIT or childRet == bret.RUNNING or args.childFinishContiCond == "CHILDFINISH_LOOP" then
            r = child:run(env)
        end

        if r == bret.FAIL then
            failCount = failCount + 1
            node:setChildRet(env, child.id, bret.FAIL)
        end

        if r == bret.SUCCESS then
            successCount = successCount + 1
            node:setChildRet(env, child.id, bret.SUCCESS)
        end
    end

    if ((args.successCondition == "SUCCEED_ON_ONE" and successCount > 0) or
        (args.successCondition == "SUCCEED_ON_ALL" and successCount == childCount)) then
        ret = bret.SUCCESS
        goto FINISH
    elseif ((args.failCondition == "FAIL_ON_ONE" and failCount > 0) or
        (args.failCondition == "FAIL_ON_ALL" and failCount == childCount)) then
        ret = bret.FAIL
        goto FINISH
    else
        return node:yield(env)
    end

    ::FINISH::
    for i = 1, childCount do
        local child = node.children[i]
        node:setChildRet(env, child.id, bret.INIT)
    end

    return ret

end

return M

`
