### ISSUE TITLE
目录结构

### ISSUE THREAD

**Issue by cloudfreexiao** [zhandouxiaojiji/behavior3lua#4]
能否调整下 目录结构 
目前 库文件 都在 lualib 目录下
这种结构 不好 放到工程里使用 还得 改一次路径
能否把他们合在一个 目录里

**Comment by zhandouxiaojiji** [comment]
好建议！这项目最初仅作为示例用，所以没考虑到库文件复用的问题。
你可以尝试调整目录结构，作为你工程的子仓库，然后提个pr给我。

**Comment by zhandouxiaojiji** [comment]
能复用的貌似也只有behavior_node.lua, behavior_tree.lua和部分通用节点吧

**Comment by cloudfreexiao** [comment]
应该是的
